"use client";
import React from "react";
import { clsx } from "clsx";
import { useState, type ButtonHTMLAttributes, type HTMLAttributes, type InputHTMLAttributes, type ReactNode } from "react";
export function Button({ className, type = "button", variant = "primary", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "danger" }) { return <button className={clsx("ml-button", className)} data-variant={variant} type={type} {...props} />; }
export function Input({ label, id, error, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string }) { const inputId = id ?? props.name; return <label className="ml-field" htmlFor={inputId}><span>{label}</span><input className="ml-input" id={inputId} aria-invalid={Boolean(error)} aria-describedby={error ? `${inputId}-error` : undefined} {...props} />{error && <small id={`${inputId}-error`} role="alert">{error}</small>}</label>; }
export function Card({ className, ...props }: HTMLAttributes<HTMLElement>) { return <section className={clsx("ml-card", className)} {...props} />; }
export function Badge({ children }: { children: ReactNode }) { return <span className="ml-badge">{children}</span>; }
export function Alert({ children, title = "Notice" }: { children: ReactNode; title?: string }) { return <div className="ml-alert" role="status"><strong>{title}</strong><div>{children}</div></div>; }
export function Skeleton({ height = "1rem" }: { height?: string }) { return <div className="ml-skeleton" style={{ height }} aria-hidden="true" />; }
export function Loader({ label = "Loading" }: { label?: string }) { return <span role="status"><span className="ml-spinner" aria-hidden="true" /><span className="sr-only">{label}</span></span>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="ml-card" role="status"><h2>{title}</h2><p>{description}</p>{action}</div>; }
export function Statistics({ label, value, trend }: { label: string; value: ReactNode; trend?: string }) { return <div className="ml-card"><small>{label}</small><strong style={{ display: "block", fontSize: "1.8rem" }}>{value}</strong>{trend && <span>{trend}</span>}</div>; }
export function Search({ label = "Search", ...props }: InputHTMLAttributes<HTMLInputElement> & { label?: string }) { return <Input label={label} type="search" {...props} />; }
export function Pagination({ page, pages, onChange }: { page: number; pages: number; onChange: (page: number) => void }) { return <nav aria-label="Pagination"><Button variant="secondary" disabled={page <= 1} onClick={() => onChange(page - 1)}>Previous</Button><span aria-live="polite"> Page {page} of {pages} </span><Button variant="secondary" disabled={page >= pages} onClick={() => onChange(page + 1)}>Next</Button></nav>; }
export function Avatar({ name, src }: { name: string; src?: string }) { return <span className="ml-badge" role={src ? "img" : undefined} aria-label={name} style={src ? { width: 36, height: 36, borderRadius: "50%", backgroundImage: `url(${src})`, backgroundSize: "cover" } : undefined}>{src ? null : name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span>; }
export function Accordion({ items }: { items: { title: string; content: ReactNode }[] }) { const [open, setOpen] = useState(0); return <div>{items.map((item, index) => <section key={item.title}><h3><button aria-expanded={open === index} onClick={() => setOpen(open === index ? -1 : index)}>{item.title}</button></h3>{open === index && <div>{item.content}</div>}</section>)}</div>; }
export function Tabs({ tabs }: { tabs: { id: string; label: string; content: ReactNode }[] }) { const [active, setActive] = useState(tabs[0]?.id); const current = tabs.find((tab) => tab.id === active); return <div><div className="ml-tabs" role="tablist">{tabs.map((tab) => <button key={tab.id} role="tab" aria-selected={tab.id === active} onClick={() => setActive(tab.id)}>{tab.label}</button>)}</div><div role="tabpanel">{current?.content}</div></div>; }
export function Timeline({ items }: { items: { title: string; detail?: string }[] }) { return <ol>{items.map((item) => <li key={item.title}><strong>{item.title}</strong>{item.detail && <p>{item.detail}</p>}</li>)}</ol>; }
