import { beforeEach, describe, expect, it, vi } from "vitest";
import { AuthenticationError } from "@medlink/platform";

const state = vi.hoisted(() => ({
  context: null as null | { correlationId: string; userId: string; tenantId: string; role: string },
}));

vi.mock("../../../../lib/request-context", () => ({
  resolveRequestContext: async () => {
    if (!state.context) throw new AuthenticationError();
    return state.context;
  },
}));

import { GET } from "./route";

function request() {
  return new Request("https://medlink.example/api/v1/context");
}

describe("GET /api/v1/context", () => {
  beforeEach(() => {
    state.context = null;
  });

  it("denies an unauthenticated request", async () => {
    const response = await GET(request());
    expect(response.status).toBe(401);
  });

  it("returns every role's own session context, including patient -- no unrelated object permission gates this", async () => {
    for (const role of ["platform_admin", "tenant_admin", "pharmacist", "pharmacy_owner", "pharmacy_staff", "inventory_manager", "provider", "patient"]) {
      state.context = { correlationId: "11111111-1111-1111-1111-111111111111", userId: "22222222-2222-2222-2222-222222222222", tenantId: "33333333-3333-3333-3333-333333333333", role };
      const response = await GET(request());
      expect(response.status).toBe(200);
      const body = await response.json();
      // correlationId is generated by the runtime dispatcher itself (from the
      // x-correlation-id header or a fresh UUID), not propagated from
      // resolveRequestContext() -- only tenantId/role are.
      expect(typeof body.data.correlationId).toBe("string");
      expect(body.data).toMatchObject({ tenantId: state.context.tenantId, role });
    }
  });
});
