import { describe,expect,it,vi } from "vitest";
import { createHash } from "node:crypto";
import { applyBootstrap,validateBootstrap } from "./bootstrap";

const products=`product_id,ingredient_id,manufacturer_id,product_name,form_id,strength,NAFDAC,product_category_id,marketing_category_id,applicant_id,approval_date,expiry_date,route_id,smpc,country_id,product_description,pack_size,biosimilar,atc,created_at,updated_at,deleted_at,status,composition,ingredient,form,applicant,route,product_category,category_name,ingredient_name,synonym,form_name,applicant_name,route_name,DT_RowIndex\n1,10,20,Medicine,30,5mg,A1,40,50,60,2025-01-01,2030-01-01,70,,,,,,,,,,active,,,,,,Drugs,Drugs,Ingredient,,Tablet,Maker,Oral,1\n`;
const manufacturers=`manufacturer_id,manufacturer_name,product_count,ingredient_count,detail_url,source_page,source_position,retrieved_at\n20,Maker,1,1,https://greenbook.nafdac.gov.ng/manufacturer/products/20,1,1,2026-08-21T00:00:00Z\n`;
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
const source=(path:string,content:string,rowCount:number,columnCount:number)=>({path,artifactUri:`nafdac-greenbook://${path}/sha256/${hash(content)}`,sha256:hash(content),rowCount,columnCount,byteSize:Buffer.byteLength(content),sourceUrl:"https://greenbook.nafdac.gov.ng/",retrievedAt:"2026-08-21T00:00:00Z"});
const manifest=(drift:{status:"none"}|{status:"review_required";reportSha256:string;reasons:string[]}={status:"none"})=>({version:"medlink-merdp-bootstrap-manifest-v1",generatedAt:"2026-08-21T00:00:00Z",target:{environment:"preview",projectRef:"abcdefghijklmnopqrst"},provenance:{acquisitionCommit:"7ad9b86e53cfd19353b637d2f43352877cfae268",authority:"NAFDAC Greenbook"},certifiedBaseline:{products:{rowCount:9008,sha256:"a".repeat(64)},manufacturers:{rowCount:1385,sha256:"b".repeat(64)}},sources:{products:source("products.csv",products,1,36),manufacturers:source("manufacturers.csv",manufacturers,1,8)},drift});
const state={medicines:0,manufacturers:0,registrations:0,rawRecords:0};
const validate=(extra={})=>validateBootstrap({manifest:manifest(),sources:{products,manufacturers},mode:"dry-run",projectRef:"abcdefghijklmnopqrst",environment:"preview",targetState:state,...extra});

describe("MERDP bootstrap safety",()=>{
  it("plans a source-only dry run without mutation",()=>{const result=validate();expect(result.plan).toMatchObject({sourceProducts:1,sourceManufacturers:1,rawRecordsExpected:2,medicinesToInsert:1,manufacturersToInsert:1,unsafeMerges:0});});
  it("fails closed on source hash or count mismatch",()=>expect(()=>validateBootstrap({manifest:{...manifest(),sources:{...manifest().sources,products:{...manifest().sources.products,rowCount:2}}},sources:{products,manufacturers},mode:"dry-run",projectRef:"abcdefghijklmnopqrst",environment:"preview",targetState:state})).toThrow(/SOURCE_MANIFEST_MISMATCH:products:rowCount/));
  it("binds the manifest to the explicit project and environment",()=>{expect(()=>validate({projectRef:"zyxwvutsrqponmlkjihg"})).toThrow("TARGET_PROJECT_MISMATCH");expect(()=>validate({environment:"test"})).toThrow("TARGET_ENVIRONMENT_MISMATCH");});
  it("refuses Production without two explicit authorizations",()=>{const production={...manifest(),target:{environment:"production",projectRef:"abcdefghijklmnopqrst"}};expect(()=>validateBootstrap({manifest:production,sources:{products,manufacturers},mode:"dry-run",projectRef:"abcdefghijklmnopqrst",environment:"production",targetState:state,allowProduction:true})).toThrow("PRODUCTION_BOOTSTRAP_NOT_AUTHORIZED");});
  it("allows drift inspection but refuses drift apply without matching report authorization",()=>{const report="c".repeat(64),drifted=manifest({status:"review_required",reportSha256:report,reasons:["manufacturer count changed"]});expect(validateBootstrap({manifest:drifted,sources:{products,manufacturers},mode:"dry-run",projectRef:"abcdefghijklmnopqrst",environment:"preview",targetState:state}).plan.sourceDrift).toBe("review_required");expect(()=>validateBootstrap({manifest:drifted,sources:{products,manufacturers},mode:"apply",projectRef:"abcdefghijklmnopqrst",environment:"preview",targetState:state})).toThrow("SOURCE_DRIFT_NOT_AUTHORIZED");});
  it("never mutates from a dry-run plan",async()=>{const target={persist:vi.fn(),converge:vi.fn()};await expect(applyBootstrap(validate(),target)).rejects.toThrow("DRY_RUN_CANNOT_MUTATE");expect(target.persist).not.toHaveBeenCalled();});
  it("applies only through certified persistence and convergence boundaries",async()=>{const report="c".repeat(64),validated=validateBootstrap({manifest:manifest({status:"review_required",reportSha256:report,reasons:["reviewed"]}),sources:{products,manufacturers},mode:"apply",projectRef:"abcdefghijklmnopqrst",environment:"preview",targetState:state,approveDriftSha256:report});const target={persist:vi.fn().mockResolvedValue({runId:"run",snapshotId:"snapshot",replay:false,rawPersisted:1,findingsPersisted:0}),converge:vi.fn().mockResolvedValue({durationMs:1,reviewCases:0,productMappings:1,manufacturerMappings:1,provenance:1,certifications:0,publications:0,events:0})};await applyBootstrap(validated,target);expect(target.persist).toHaveBeenCalledTimes(2);expect(target.converge).toHaveBeenCalledOnce();});
});
