-- Wave 3.1-3.4 conversation, identity, interaction, and durable orchestration.
create table public.conversation_sessions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),channel text not null check(channel='whatsapp'),channel_identity_hash text not null,patient_id uuid references auth.users(id),status text not null check(status in('active','waiting_for_human','completed','expired')),workflow_run_id uuid references public.workflow_runs(id),version integer not null default 1,consented_at timestamptz,opted_out_at timestamptz,last_activity_at timestamptz not null default now(),created_at timestamptz not null default now(),unique(id,organization_id),unique(organization_id,channel,channel_identity_hash));
create table public.conversation_messages(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),session_id uuid not null,direction text not null check(direction in('inbound','outbound')),provider_message_id text not null,kind text not null check(kind in('text','image','document','interactive')),content_ciphertext text,media_object_path text,occurred_at timestamptz not null,created_at timestamptz not null default now(),foreign key(session_id,organization_id)references public.conversation_sessions(id,organization_id),unique(organization_id,provider_message_id));
create table public.conversation_handoffs(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),session_id uuid not null,reason text not null,status text not null check(status in('requested','accepted','resolved')),assigned_to uuid references auth.users(id),created_at timestamptz not null default now(),resolved_at timestamptz,foreign key(session_id,organization_id)references public.conversation_sessions(id,organization_id));
create index conversation_session_activity_idx on public.conversation_sessions(organization_id,status,last_activity_at desc);
create index conversation_message_timeline_idx on public.conversation_messages(session_id,occurred_at);
alter table public.conversation_sessions enable row level security;alter table public.conversation_messages enable row level security;alter table public.conversation_handoffs enable row level security;
create policy conversation_staff_read on public.conversation_sessions for select to authenticated using(public.is_organization_member(organization_id));
create policy conversation_messages_staff_read on public.conversation_messages for select to authenticated using(public.is_organization_member(organization_id));
create policy conversation_handoffs_staff_all on public.conversation_handoffs for all to authenticated using(public.has_organization_role(organization_id,array['platform_admin','tenant_admin','pharmacist']::public.member_role[]))with check(public.has_organization_role(organization_id,array['platform_admin','tenant_admin','pharmacist']::public.member_role[]));
create trigger conversation_messages_append_only before update or delete on public.conversation_messages for each row execute function public.prevent_enterprise_event_mutation();
